# Generated by Django 2.2.7 on 2019-11-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveplanuser',
            name='ThreeMonthCost',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='moveplanuser',
            name='WorkDays',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='moveplanuser',
            name='YearAllowance',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='moveplanuser',
            name='YearPerformance',
            field=models.IntegerField(default=1),
        ),
    ]
