# Generated by Django 2.2.6 on 2019-11-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_retirecalculate_retireexpected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicePension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WantYear', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvestmentPay', models.CharField(max_length=100)),
                ('PensionRateReturn', models.CharField(max_length=100)),
                ('MonthCompound', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShowPensionDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RateReturnDC', models.CharField(max_length=100)),
            ],
        ),
    ]
