# Generated by Django 2.2.6 on 2019-11-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_choicepension_privacypension_showpensiondc'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypension',
            name='PensionCategoryChoices',
            field=models.CharField(choices=[('P1', '연금보험'), ('P2', '변액연금보험'), ('P3', '연금저축보험')], default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='showpensiondc',
            name='InvestmentChoices',
            field=models.CharField(choices=[('i1', '10'), ('i2', '15'), ('i3', '20')], default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='showpensiondc',
            name='YearDCChoices',
            field=models.CharField(choices=[('y1', '10'), ('y2', '15'), ('y3', '20')], default=0, max_length=60),
        ),
    ]
