# Generated by Django 2.2.1 on 2019-11-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20191110_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetireSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OneYearChoice', models.CharField(choices=[('t1', '네'), ('t2', '아니오')], max_length=60)),
                ('RestTear', models.CharField(max_length=100)),
                ('AddMonth', models.CharField(max_length=100)),
            ],
        ),
    ]
