# Generated by Django 2.2.6 on 2019-11-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_retireseason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypension',
            name='PensionCategoryChoices',
            field=models.CharField(choices=[('p1', '연금보험'), ('P2', '변액연금보험'), ('P3', '연금저축보험')], default=0, max_length=60),
        ),
    ]
