# Generated by Django 2.2.6 on 2019-11-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20191117_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypension',
            name='PensionCategoryChoices',
        ),
        migrations.AlterField(
            model_name='privacypension',
            name='InvestmentPay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='privacypension',
            name='MonthCompound',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='privacypension',
            name='PensionRateReturn',
            field=models.IntegerField(),
        ),
    ]
