# Generated by Django 2.2.6 on 2019-11-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoicePension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WantYear', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PensionCategoryChoices', models.CharField(choices=[('P1', '연금보험'), ('P2', '변액연금보험'), ('P3', '연금저축보험')], default=0, max_length=60)),
                ('InvestmentPay', models.CharField(max_length=100)),
                ('PensionRateReturn', models.CharField(max_length=100)),
                ('MonthCompound', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RetireCalculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreeMonthCost', models.IntegerField()),
                ('YearPerformance', models.IntegerField()),
                ('YearAllowance', models.IntegerField()),
                ('WorkDays', models.IntegerField()),
                ('RetireExpected', models.CharField(default='example', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RetireSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OneYearChoice', models.CharField(choices=[('t1', '네'), ('t2', '아니오')], max_length=60)),
                ('RestTear', models.CharField(max_length=100)),
                ('AddMonth', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShowPensionDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvestmentChoices', models.CharField(choices=[('i1', '10'), ('i2', '15'), ('i3', '20')], default=0, max_length=60)),
                ('YearDCChoices', models.CharField(choices=[('y1', '10'), ('y2', '15'), ('y3', '20')], default=0, max_length=60)),
                ('RateReturnDC', models.CharField(max_length=100)),
            ],
        ),
    ]
