# Generated by Django 2.2.6 on 2019-11-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoicePension',
        ),
        migrations.DeleteModel(
            name='PrivacyPension',
        ),
        migrations.DeleteModel(
            name='RetireCalculate',
        ),
        migrations.DeleteModel(
            name='RetireSeason',
        ),
        migrations.DeleteModel(
            name='ShowPensionDC',
        ),
    ]
